# Based on Synthetify's workflow
# https://github.com/Synthetify/synthetify-protocol/blob/master/.github/workflows/test.yml

name: Anchor Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gootools/anchor-actions@v0.7
